version: 2
updates:
  - package-ecosystem: pub
    directory: /
    schedule:
      interval: daily
      timezone: Asia/Tokyo
    groups:
      patch-updates:
        update-types:
          - patch
